Repository Black-Dot-2024/Zeitgeist-FrontEnd, pull requests merged in 2024-05, with the labels that each got.

#82 Feat/rf02 assigned tasks
  src/components/common/Error.tsx
  src/components/modules/Task/TableTask/TaskTable.tsx
  src/hooks/useHttp.ts
  src/pages/Auth/index.tsx
  src/pages/Tasks/index.tsx
  src/types/task.ts
Labels: enhancement

#118 feat(createTask): create task working properly :)
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/pages/Projects/details.tsx
  src/pages/Tasks/new.tsx
  src/utils/constants.ts
Labels: Zeitgeist

#126 feat(createTask): fixed project name field so that it is automaticall…
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/pages/Tasks/new.tsx
Labels: Zeitgeist

#137 feat(filter): filter archived projecs
  src/components/modules/Projects/ClientDropdown.tsx
  src/components/modules/Projects/ProjectCard.tsx
  src/pages/Projects/details.tsx
  src/pages/Projects/edit.tsx
  src/pages/Projects/main.tsx
  src/types/project.ts
Labels: Zeitgeist

#171 Fix: RF05 Bugs
  src/components/common/ModifyButton.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Labels: Zeitgeist

#172 fix(hours): show worked hours in project details
  src/components/modules/Task/TaskListTable.tsx
  src/pages/Clients/index.tsx
  src/pages/Projects/details.tsx
  src/pages/Tasks/update.tsx
  src/utils/methods.ts
Labels: bug, enhancement

#170 Feat/rf26 delete task
  src/components/common/CancelButton.tsx
  src/components/common/DeleteButton.tsx
  src/components/common/TaskActionsMenu.tsx
  src/components/modules/Task/TableTask/TaskTable.tsx
  src/components/modules/Task/TaskListTable.tsx
  src/hooks/useDeleteTask.ts
  src/pages/Projects/details.tsx
  src/pages/Tasks/assigned.tsx
  src/pages/Tasks/task-detail.tsx
Labels: enhancement, Zeitgeist

#181 fix(RF62): Updated '/clients/:id' to be accessible globally
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Clients/index.tsx
Labels: enhancement, Zeitgeist

#188 fix(company): add back button and remove delete button
  src/components/common/Layout.tsx
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Clients/index.tsx
Labels: bug

#189 Fix/company phone number
  src/components/modules/Clients/EditClientFormModal.tsx
  src/components/modules/Clients/NewClientFormModal.tsx
Labels: bug, enhancement

#191 fix(RF62): Added 'key' to company card to solve console warnings
  pnpm-lock.yaml
  src/pages/Home/index.tsx
Labels: enhancement, Zeitgeist

#194 Fix/rf20 Vista Reporte Projecto
  src/pages/Projects/report-pdf.tsx
  src/pages/Projects/report.tsx
Labels: Zeitgeist, design

#195 fix(session): keep user session open, use localStorage instead of ses…
  src/App.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/modules/Employees/EmployeeeTable.tsx
  src/hooks/useArchiveClient.ts
  src/hooks/useDeleteEmployee.ts
  src/hooks/useDeleteTask.ts
  src/hooks/useHttp.ts
  src/hooks/useNewProject.ts
  src/pages/Auth/index.tsx
  src/pages/Projects/main.tsx
  src/pages/Projects/report.tsx
Labels: bug

#198 fix(RF62): Fixed broken links from ClientsDetails
  src/pages/Home/index.tsx
Labels: Zeitgeist, design

#201 fix(taskDetail): removed 2 2 left behind
  src/pages/Tasks/task-detail.tsx
Labels: bug, Zeitgeist

#202 Fix/rf62 vista
  src/components/modules/Home/ClientCard.tsx
Labels: enhancement, Zeitgeist

#174 Mejorar estilos, Cambiar el loader e Implementar animaciones
  package.json
  pnpm-lock.yaml
  postcss.config.cjs
  postcss.config.js
  public/fonts/Didot Regular.ttf
  public/fonts/Gotham Light Regular.otf
  public/fonts/Gotham Regular.otf
  src/assets/no-data.json
  src/components/common/ComponentPlaceholder.tsx
  src/components/common/Loader.tsx
  src/components/modules/Clients/ClientCard.tsx
  src/components/modules/Employees/Table.tsx
  src/components/modules/Task/TaskListTable.tsx
  src/hooks/useNewProject.ts
  src/index.css
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Clients/index.tsx
  src/pages/Home/index.tsx
  src/pages/Projects/ProjectsClientList.tsx
  src/pages/Projects/main.tsx
  src/pages/Tasks/assigned.tsx
  src/pages/Tasks/task-detail.tsx
  tailwind.config.js
Labels: enhancement, Zeitgeist

#190 Fix/clients view
  src/components/common/CardsGrid.tsx
Labels: bug, Zeitgeist

#208 Fix/RF16: Warning en consola: Project Details
  src/components/modules/Task/TaskListTable.tsx
Labels: Zeitgeist, design

#219 refactor(GenericDropdownStyles): updated the generic dropdown styles
  src/colors.tsx
  src/components/common/GenericDropdown.tsx
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/TableTask/TaskTable.tsx
  src/components/modules/Task/TaskListTable.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
  src/pages/Projects/details.tsx
Labels: enhancement, Zeitgeist, design

#220 fix(layout): added New Task when creating a task
  src/App.tsx
  src/components/common/Layout.tsx
  src/pages/Projects/details.tsx
Labels: bug, Zeitgeist, design

#258 Fix/rf18 modificar cliente
  src/components/modules/Clients/EditClientFormModal.tsx
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/utils/methods.ts
Labels: bug

#262 fix(text): truncate titles and names when length > 50
  src/components/common/ClientCard.tsx
  src/components/modules/Home/ClientCard.tsx
  src/components/modules/Projects/ProjectCard.tsx
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Clients/index.tsx
  src/pages/Projects/details.tsx
  src/utils/methods.ts
Labels: bug

#263 refactor(GenericDropdownStyles): new styles for dropdown
  src/components/common/GenericDropdown.tsx
Labels: Zeitgeist, design

#265 fix(typo): fixed typo
  src/components/modules/Task/NewTask/NewTaskForm.tsx
Labels: bug, Zeitgeist, design

#279 refactor(GenericDropdown): fixed arrow icon not opening the menu
  src/components/common/GenericDropdown.tsx
Labels: Zeitgeist, design

#297 fix(RF21): Project with '.' downloads with wrong extension
  src/pages/Projects/report.tsx
Labels: enhancement, Zeitgeist

#303 fix(RF56): Archive/Unarchive now redirects properly to 'Clients' page
  src/components/common/ArchiveModal.tsx
  src/pages/Clients/ClientDetails/ClientDetails.tsx
Labels: enhancement, Zeitgeist

#347 fix(RF05): Task Redirect onClick 'Edit'
  src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
  src/components/modules/Task/TaskListTable.tsx
Labels: Zeitgeist, design

#349 fix(RF17): ClientDeets Truncate too long names
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Projects/main.tsx
Labels: Zeitgeist, design

#350 fix(RF27): Responsive Cards for Projects & Clients
  src/components/common/ClientCard.tsx
  src/components/modules/Home/ClientCard.tsx
  src/components/modules/Projects/ProjectCard.tsx
Labels: Zeitgeist, design

#351 fix(RF56): ArchiveModal Alert Color/Icon
  src/components/common/ArchiveModal.tsx
  src/pages/Clients/ClientDetails/ClientDetails.tsx
Labels: Zeitgeist, design

#352 fix(RF15): validate fields while editing project
  src/components/modules/Projects/ClientDropdown.tsx
  src/hooks/useNewProject.ts
  src/pages/Projects/edit.tsx
  src/types/project.ts
Labels: bug

#357 Fix/create task assignees
  src/pages/Tasks/new.tsx
Labels: bug, Zeitgeist, fix

#356 Fix/rf12 crear proyecto
  src/components/common/ComponentPlaceholder.tsx
  src/hooks/useNewProject.ts
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Projects/ProjectsClientList.tsx
  src/pages/Projects/edit.tsx
  src/pages/Projects/main.tsx
  src/pages/Projects/new.tsx
  src/pages/Projects/report.tsx
Labels: bug, enhancement

#362 Fix/proyectos
  src/pages/Clients/index.tsx
  src/pages/Projects/main.tsx
Labels: Zeitgeist

#358 fix(header): place date before title
  src/components/common/Header.tsx
Labels: enhancement

#363 fix(RF15): Update Navigate link when Update/Cancel project details
  src/pages/Projects/edit.tsx
Labels: Zeitgeist, design

#365 fix(RF25): Specific messages for missing fields on Snackbar
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Labels: Zeitgeist, design

#353 Fix/rf01
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/TaskListTable.tsx
  src/pages/Projects/details.tsx
Labels: Zeitgeist, design

#359 Fix/assigned tasks
  src/colors.tsx
  src/components/common/GenericDropdown.tsx
  src/pages/Tasks/assigned.tsx
Labels: bug, Zeitgeist, fix

#364 refactor(assigned): increased font size
  src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
  src/pages/Tasks/assigned.tsx
Labels: Zeitgeist

#376 fix(RF62): Change 'Clients to 'My Clients'
  src/pages/Home/index.tsx
Labels: Zeitgeist, design

#384 fix(RF62): Task Detail Responsiveness
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Tasks/task-detail.tsx
Labels: Zeitgeist, design

#387 fix(RF25): Description Scroll
  src/components/modules/Task/NewTask/NewTaskForm.tsx
Labels: Zeitgeist, design

#390 fix(RF25): Add notify to user when task deletes successfully
  src/pages/Projects/details.tsx
  src/pages/Tasks/assigned.tsx
Labels: Zeitgeist, design

#396 fix(RF25): Add workedhours validation to prevent 'undefined'
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/pages/Tasks/task-detail.tsx
Labels: Zeitgeist, design

#400 fix(RF05): Updated Datevalidators for start & due date
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Labels: Zeitgeist, design

#404 Adding tooltips to icons
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Clients/index.tsx
  src/pages/Projects/details.tsx
  src/pages/Projects/main.tsx
  src/pages/Tasks/task-detail.tsx
Labels: Zeitgeist, design

#406 Fix/sidebar
  src/components/common/SideBar.tsx
Labels: bug, Zeitgeist

#411 Fix/create task employee dropdown
  src/pages/Tasks/new.tsx
  src/pages/Tasks/update.tsx
Labels: Zeitgeist, fix

#417 fix(RF27RF57): ArchiveClients RBAC
  src/pages/Clients/ClientDetails/ClientDetails.tsx
  src/pages/Clients/index.tsx
Labels: Zeitgeist, design

#422 fix(RF56): Archive/Unarchive button depends on archive attrib
  src/pages/Clients/ClientDetails/ClientDetails.tsx
Labels: Zeitgeist, design

#438 RF05-25: Tasks now POST correctly when employee or end date are null. Button now disables when it is posting to avoid exploits.
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
  src/types/task.ts
Labels: fix

#444 Refactor/Console warnings & Consistency between files
  package.json
  pnpm-lock.yaml
  src/components/common/ComponentPlaceholder.tsx
  src/components/common/Layout.tsx
  src/components/common/NotFound.tsx
  src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
  src/components/modules/Task/TaskListTable.tsx
  src/pages/Clients/ClientDetails/index.tsx
  src/pages/Clients/details.tsx
  src/pages/Clients/index.tsx
  src/pages/Clients/main.tsx
  src/pages/Projects/ProjectsClientList.tsx
  src/pages/Projects/details.tsx
  src/pages/Tasks/details.tsx
  src/pages/Tasks/edit.tsx
  src/pages/Tasks/index.tsx
  src/pages/Tasks/main.tsx
  src/utils/constants.ts
Labels: enhancement, Zeitgeist, design

#449 fix(RF27): Loader not displaying properly
  src/pages/Clients/main.tsx
Labels: Zeitgeist, design

#450 fix(page): report
  src/pages/Projects/report.tsx
Labels: Zeitgeist, design

#473 Refactor/Responsiveness v1.0
  src/components/common/ClientCard.tsx
  src/components/common/GenericDropdown.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/SideBar.tsx
  src/components/modules/Employees/EmployeeeTable.tsx
  src/pages/Clients/details.tsx
  src/pages/Clients/main.tsx
  src/pages/Employees/index.tsx
  src/pages/Home/index.tsx
  src/pages/Projects/main.tsx
Labels: enhancement, Zeitgeist, design

#480 fix(GenericDropdown): fixed scrollable in Y axis after change from mu…
  src/components/common/GenericDropdown.tsx
Labels: bug, design, fix

#481 fix(date): fix date in client
  src/components/modules/Clients/EditClientFormModal.tsx
  src/pages/Clients/details.tsx
Labels: bug, fix

#484 Refactor/Responsiveness v2.0
  src/components/common/Layout.tsx
  src/components/modules/Clients/EditClientFormModal.tsx
  src/components/modules/Clients/NewClientFormModal.tsx
  src/components/modules/Clients/details.module.css
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
  src/pages/Clients/details.tsx
  src/pages/Clients/main.tsx
  src/pages/Employees/index.tsx
  src/pages/Home/index.tsx
  src/pages/Projects/details.tsx
  src/pages/Projects/edit.tsx
  src/pages/Projects/main.tsx
  src/pages/Projects/new.tsx
  src/pages/Tasks/details.tsx
  src/pages/Tasks/main.tsx
Labels: enhancement, Zeitgeist, design

#486 fix(RF05): Snackbar residual code
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
Labels: bug, Zeitgeist, design

#490 Fix/done status tasks
  src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
  src/pages/Tasks/main.tsx
Labels: bug, fix

#452 feat(EmployeeView): department is set for employee
  src/components/modules/Employees/EmployeeeTable.tsx
  src/types/department.ts
Labels: enhancement, Zeitgeist

#494 Refactor/Responsiveness v3.0
  src/components/common/ColorChip.tsx
  src/pages/Projects/report.tsx
Labels: enhancement, Zeitgeist, design

#500 fix(RF26): Console Error: Trying to delete employee on TaskDelete
  src/components/common/DeleteModal.tsx
  src/pages/Tasks/details.tsx
Labels: bug, Zeitgeist

#503 feat(TaskListTable): added missing employee column. Could not make th…
  src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
  src/components/modules/Task/TaskListTable.tsx
  src/pages/Projects/details.tsx
  src/pages/Tasks/main.tsx
Labels: Zeitgeist

#509 Refactor/Validators in forms
  src/components/common/Layout.tsx
  src/components/modules/Clients/EditClientFormModal.tsx
  src/components/modules/Clients/NewClientFormModal.tsx
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
  src/pages/Projects/edit.tsx
  src/pages/Projects/new.tsx
Labels: enhancement, Zeitgeist, design

#513 fix(projectDetailsTasks): added styles and changed to display one nam…
  src/components/modules/Task/TaskListTable.tsx
Labels: Zeitgeist

#550 fix(RF20): Add 'January' as default month to the filter
  src/pages/Projects/report.tsx
Labels: enhancement, Zeitgeist, design

#554 fix(RF20): Add 'January' as default month to the filter
  src/pages/Projects/report.tsx
Labels: enhancement, Zeitgeist, design

#584 Feat/Expenses/RF32: Expense Report View
  src/App.tsx
  src/components/common/Layout.tsx
  src/components/modules/Expenses/ExpensesTable.tsx
  src/components/modules/Expenses/StatusChip.tsx
  src/pages/Expenses/details.tsx
  src/pages/Expenses/index.tsx
  src/types/expense.ts
  src/utils/constants.ts
Labels: enhancement, Zeitgeist

#609 Feat/responsiveness
  src/App.css
  src/assets/images/bg-mobile.png
  src/components/common/AddButton.tsx
  src/components/common/ArchiveModal.tsx
  src/components/common/CardContainer.tsx
  src/components/common/ClientCard.tsx
  src/components/common/ComponentPlaceholder.tsx
  src/components/common/DeleteModal.tsx
  src/components/common/GenericInput.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/ModalEditConfirmation.tsx
  src/components/common/ModifyButton.tsx
  src/components/common/SearchBar.tsx
  src/components/common/SideBar.tsx
  src/components/modules/Clients/ClientFormModal.tsx
  src/components/modules/Projects/ChipWithLabel.tsx
  src/components/modules/Projects/ProjectCard.tsx
  src/components/modules/Task/NewTask/TableTask/TaskRow.tsx
  src/components/modules/Task/NewTask/TableTask/TaskTable.tsx
  src/components/modules/Task/TaskListTable.tsx
  src/main.tsx
  src/pages/Auth/index.tsx
  src/pages/Clients/details.tsx
  src/pages/Clients/main.tsx
  src/pages/Employees/index.tsx
  src/pages/Home/index.tsx
  src/pages/Projects/details.tsx
  src/pages/Projects/main.tsx
  src/pages/Projects/new.tsx
  src/pages/Projects/report.tsx
  src/pages/Tasks/details.tsx
  tsconfig.json
Labels: bug, design

#608 fix(RF32): Redirect on 403
  src/pages/Expenses/details.tsx
Labels: enhancement

#600 Fix/auth
  src/components/common/SideBar.tsx
  src/config/firebase.config.ts
  src/pages/Auth/index.tsx
Labels: enhancement, fix

#620 Fix/RF32 RedirectOn403
  src/pages/Expenses/details.tsx
Labels: fix

#617 Fix/tasks date
  src/components/modules/Task/NewTask/NewTaskForm.tsx
  src/components/modules/Task/UpdateTask/UpdateTaskForm.tsx
  src/hooks/useProjectForm.ts
  src/hooks/useTaskForm.ts
  src/pages/Projects/details.tsx
  src/pages/Projects/edit.tsx
  src/pages/Projects/new.tsx
  src/pages/Tasks/details.tsx
Labels: bug

#627 fix(RF32): Responsiveness
  src/components/modules/Expenses/ExpensesTable.tsx
  src/pages/Expenses/details.tsx
Labels: enhancement, fix

#630 fix(layout): fix sidebar filling full height
  src/components/common/Layout.tsx
Labels: bug, design

#633 feat/RF40 modificar estatus viatico
  src/components/common/CreateConfirmationModal.tsx
  src/components/common/SideBar.tsx
  src/hooks/useExpenseForm.ts
  src/pages/Expenses/details.tsx
  src/pages/Expenses/main.tsx
  src/pages/Projects/report-pdf.tsx
  src/pages/Projects/report.tsx
Labels: enhancement
