Repository Black-Dot-2024/Zeitgeist-FrontEnd, pull requests merged in 2024-06, with the labels that each got.

#642 fix(ui): add responsiveness
  src/components/common/Layout.tsx
  src/components/common/SideBar.tsx
  src/pages/Expenses/details.tsx
  src/pages/Projects/report.tsx
Labels: bug, fix

#654 fix(reports): reload report page when proyect status changes
  src/pages/Projects/details.tsx
  src/pages/Projects/report.tsx
Labels: bug

#638 [RF34]: Descargar reporte de viático
  src/components/modules/Expenses/ExpensesTable.tsx
  src/pages/Expenses/details.tsx
  src/pages/Expenses/report.tsx
  src/pages/Projects/main.tsx
Labels: enhancement

#668 Fix/rf35 modal
  src/pages/Expenses/details.tsx
  src/pages/Expenses/report.tsx
  src/pages/Projects/report.tsx
Labels: bug

#688 fix(auth): redirect user with no role to login
  src/components/common/ProtectedRoute.tsx
Labels: bug
